### ISSUE TITLE
refactor all non-breaking changes into the `3` branch

### ISSUE THREAD

**Issue by sminnee** [wernerkrauss/silverstripe3-php7#2]
Many of the changes that the patch introduces would be acceptable to include in the `3` branch of silverstripe/framework.

If we apply these as a PR to the main repo, then our patch file can be smaller, reducing the chance of conflicts.

I think that the patch should be limited to renaming `Int` to `DBInt` and `Float` to `DBFloat`. It should possibly also include the removal of SimpleTest, but I'm not sure what the impact of fixing this in the main `3` branch would be.

**Comment by wernerkrauss** [comment]
I just took the work of @lekoala and @markguinn and made it easily installable. See README.md and https://github.com/silverstripe/silverstripe-framework/compare/master...markguinn:patch-3-327

I'd be happy if this module becomes obsolete and latest SS3 works with PHP7 out of the box. Of course I could create a PR with the relevant parts.

**Comment by lekoala** [comment]
I just discovered this great module! a composer patch is a much better solution than my current module.

I also believe that SilverStripe 3 should support PHP7 out of the box. I'm not even sure that the Int/DBInt problem is really a problem. Who is actually doing "new Int" or "new Float" in their code? I believe the injector should be handle most of theses problems. Or if really needed, is it not possible to conditionnal declare theses classes if php < v7?

**Comment by lerni** [comment]
I use this in production with quite a few sites and it performs great! I would appreciate it very much, if this gets merged into 3. I had troubles making the patch-thing work on some production server. ATM you have to use "--ignore-platform-reqs" with composer to run php7 on CLI and this is what I recommend, otherwise you run into weird issues if you have a "silverstripe-cache" directory in webroot because of different php-versions.

See also:
http://silverstrip.es/blog/more-speed-with-php7-on-silverstripe-3/

**Comment by wernerkrauss** [comment]
Done in SilverStripe 3.6
